name: pyf-check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: hexlet-code
        run: |
          pip install uv
          make install

      - name: Run linter
        working-directory: hexlet-code
        run: make lint

      - name: Run tests and collect coverage
        working-directory: hexlet-code
        run: make test-coverage

      - name: Publish code coverage
        run: |
          curl -L https://github.com > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
        
      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/hexlet-code/coverage.xml:pycoverage
          debug: true